### ISSUE TITLE
Add tests to pypi tarball

### ISSUE THREAD

**Issue by asagratini** [hvac/hvac#1011]
Hello team,
while working on updating hvac version FreeBSD port [1], we noticed that tarball downloaded from pypi.org does not have test suite, which is instead available on this github repo.

Ideally, we'd like to have that included also in pypi file: is this something you can consider adding?

[1] https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272060

Let us know if you need anything else.
Thank you

**Comment by briantist** [comment]
Hi @asagratini , thanks for opening this! 

This seems reasonable and I'll look to add this. I did a little bit of preliminary research and from what I can tell adding tests to the sdist is pretty common, since we're using `poetry` I guess we will do it somewhat as described here:
- https://github.com/python-poetry/poetry/pull/1133#issue-449461453

If you have any additional background or information that would be helpful too. I'm particularly interested in whether previous versions of `hvac` did include the tests, so I can try to understand why/how they were removed.

I suspect it may have been an unintended consequence of us moving to poetry:
- https://github.com/hvac/hvac/pull/854

Since we've already merged some changes to `main` that require a minor version, the next expected version of `hvac` is `1.2.0`, and I'll look to get this resolved for that release if possible.
