### ISSUE TITLE
Vault Initialization fails when using azurekeyvault for auto unsealing

### ISSUE THREAD

**Issue by shettyvaishak** [hvac/hvac#1030]
I have a vault server setup on HA using raft storage and azure key vault for auto unsealing. I am trying to automate the process of configuring vault using HVAC

I am trying to initialize vault by using 
```
client.sys.initialize(
                    stored_shares=5, recovery_shares=5,
                    recovery_threshold=3
                    )
```

but i am getting the below error 
`parameters secret_shares,secret_threshold not applicable to seal type azurekeyvault, on put https://<HOST>/v1/sys/init` 

According to the docs when using KMS to unseal vault, recovery_keys should be passed when making the init request instead of secret_shares and secret_threshold 

https://github.com/hashicorp/vault/issues/17551

But in the code i see secret_shares, secret_threshold is added regardless and is always sent with default values when initializing vault 
```
        params = {
            "secret_shares": secret_shares,
            "secret_threshold": secret_threshold,
            "root_token_pgp_key": root_token_pgp_key,
        }
```

With this logic vault init will not work when using KMS for auto unseal or am i missing something

**Comment by therealjsie** [comment]
We have run into this as well, the violating code is [here](https://github.com/hvac/hvac/blob/b52ed1933336e497c0e45d8d7d94fed1dbaee84e/hvac/api/system_backend/init.py#L76-L80). This seems easy to adapt, but I'm not sure if this would break other use cases when removing these default values.

Using `requests` lib, this can easily be worked around (for now) like this: 
```
params = {"recovery_shares": recovery_shares, "recovery_threshold": recovery_threshold}
init_api = f"{vault_client.url}/v1/sys/init"
response = requests.post(url=init_api, json=params)

if response.status_code > 400:
    response.raise_for_status()
```

**Comment by briantist** [comment]
Thanks @shettyvaishak and @therealjsie for bringing this up and adding supporting information.

This is a pretty unfortunate situation, the docs are still very unclear (I would say, "wrong") about this since they still say that `secret_shares` and `secret_threshold` are "required" without any indication of when they cannot be used. I would also say that this section does not adequately explain the point either: https://developer.hashicorp.com/vault/docs/concepts/seal#recovery-key

The parameter swaps you and the other folks in the Vault issue reported seems to have been confirmed by HC too: https://github.com/hashicorp/vault/issues/17551#issuecomment-1340027559

It feels like there are two very different init flows and that it should have been split in Vault to different endpoints, but alas... we have to figure out how to handle this in `hvac`.

---

If we change the default values to `None` , it'll be a breaking change for anyone relying on them.

I am thinking about adding logic to the call that will check if both pairs of the mutually exclusive parameters are `None`: if so, it can set the "original" defaults, and otherwise it takes the parameters as is.

That should make the auto-unseal calls work, allow for the explicit non-auto-unseal parameters to also work, and leave naked calls to still have the same behavior they do now.

The only other question in my mind is whether we deprecate setting any default for `secret_shares` and `secret_threshold` so that in the future you always need to provide some explicit value.

**Comment by briantist** [comment]
@shettyvaishak @therealjsie I have a PR up to address this:
- #1063 

If either of you have a moment, it would be very helpful if you're able to test out this change. You can install `hvac` directly from the PR branch like so:
```console
pip install https://github.com/briantist/hvac/archive/sys/init-auto-unseal.zip
```

**Comment by vaishakshetty30** [comment]
@briantist This is the same account as @shettyvaishak , I seem to have lost access to my previous account because of bad 2FA setup.

I tested out vault init on a cluster using raft HA and azurekeyvault for auto unseal using hvac from your branch with the below code and it was able to initialize vault successfully.

```
import hvac

vaultClient = hvac.Client(
    url="<url>",
    verify=True
)

if vaultClient.sys.is_initialized():
    print("Initialized")
else:
    resp = vaultClient.sys.initialize(recovery_shares=5, recovery_threshold=3)
    print(resp)
```
