### ISSUE TITLE
Hvac cannot be installed off-architecture

### ISSUE THREAD

**Issue by dpedu** [hvac/hvac#1038]
Hvac is pure python and can be successfully used on any processor architecture. However, trying to install `hvac` off-architecture fails because it requires a dependency that is not correctly tagged.

Pip supports various flags that cause it to download and install versions of modules that are different from the architecture from the host running Pip.

This is useful for building programs in situations where the build system architecture does not match where the program will run. A real world example of this is AWS Lambda. I could be building my program on a mac and need to install the linux x86 or linux arm64 version of a package so that it is able to run on AWS Lambda.

If `hvac` is included in my requirements and I try to install them using this approach:

```
pip3 install --platform manylinux2014_x86_64 --python-version 3.9 --only-binary=:all: --target ./outdir hvac==1.1.1
```

The install fails with:

```
Collecting hvac==1.1.1
  Using cached hvac-1.1.1-py3-none-any.whl (144 kB)
ERROR: Could not find a version that satisfies the requirement pyhcl<0.5.0,>=0.4.4 (from hvac) (from versions: none)
ERROR: No matching distribution found for pyhcl<0.5.0,>=0.4.4
```

...because `hvac` depends on this improperly tagged version of `pyhcl`.

I have opened virtuald/pyhcl#87 to fix the tagging on that module, but `hvac` will need to update its dependency to the updated version, when it comes around.

Another option would be to make the dependency on `pyhcl` optional, as it is not needed for most of `hvac`'s functions.

**Comment by briantist** [comment]
Hi @dpedu thanks for opening this! It looks like `pyhcl` released a wheel for `0.4.5` which is still within our constraint range, so this is probably working for you without changes now, is that correct?

Either way, I think that you're right about `pyhcl` being an optional dependency; in fact it used to be, and it seems we changed that in https://github.com/hvac/hvac/pull/854 when we switched to poetry. I don't recall this being an intentional change, I think it was just an oversight, but I would like to make it optional again because it really is not needed in most cases.

I think I will look to make this change for the `v2.0.0` release.
