### ISSUE TITLE
Add support for sys/policies endpoint

### ISSUE THREAD

**Issue by tot19** [hvac/hvac#1096]
Would like to open a PR to add role governing and endpoint governing policies. Enterprise only feature. Please let me know if I am good to proceed! Thanks

https://developer.hashicorp.com/vault/api-docs/system/policies

**Comment by briantist** [comment]
Hi @tot19 , thanks for opening this and considering this addition. Please also read the discussion here:
- https://github.com/hvac/hvac/issues/1025

**Comment by tot19** [comment]
Thank you for sharing that. My thought here would be to create a new class for /sys/policies. The reason being is that these new policy types require different arguments and are entirely distinct from the usual ACL policies written in HCL. These policies use Consul. 

To avoid confusion + having 2 methods to perform the same action, I think I would only add support for the egp and rgp routes. I would leave out all ACL related routes under /sys/policies entirely.

What are your thoughts on this approach?

**Comment by briantist** [comment]
I like the new class approach. I would like us to also have ACL routes on the class. Although it means having 2 ways to configure ACLs, that reflects the fact that Vault has 2 ways to do it. And since a particular user/token may have permission to create policies only via one path or the other, we have to support both.

You are not obligated to add ACL support in your PR if you don't want to, but as a library we will need to support the alternate ACL path to support Vault configurations where only one or the other path is allowed (that's ultimately what #1025 was about).

Thanks for your interest in this issue!

**Comment by tot19** [comment]
I'll add ACL as well. Thanks for confirming!
