### ISSUE TITLE
Some tests in test_health.py are flaky

### ISSUE THREAD

**Issue by yan12125** [hvac/hvac#1141]
When I run the test suite of hvac (as part of building [python-hvac Arch Linux package](https://gitlab.archlinux.org/archlinux/packaging/packages/python-hvac/-/blob/main/PKGBUILD)), some tests in `tests/integration_tests/api/system_backend/test_health.py` fail with `[Errno 111] Connection refused` from time to time.

```
=========================== short test summary info ============================
ERROR tests/integration_tests/api/system_backend/test_health.py::TestHealth::test_read_health_status_0_default_params
ERROR tests/integration_tests/api/system_backend/test_health.py::TestHealth::test_read_health_status_1_unsealed_standby_node_HEAD_method
ERROR tests/integration_tests/api/system_backend/test_health.py::TestHealth::test_read_health_status_2_unsealed_standby_node_GET_method
ERROR tests/integration_tests/api/system_backend/test_health.py::TestHealth::test_read_health_status_3_sealed_standby_node_HEAD_method
ERROR tests/integration_tests/api/system_backend/test_health.py::TestHealth::test_read_health_status_4_sealed_standby_node_GET_method
ERROR tests/integration_tests/api/system_backend/test_health.py::TestHealth::test_read_health_status_5_GET_method
=========== 1437 passed, 53 skipped, 25 warnings, 6 errors in 43.73s ===========
```

Here are complete logs: [test-failures.txt](https://github.com/hvac/hvac/files/14570186/test-failures.txt)

Could you have a look?

**Comment by briantist** [comment]
Hi @yan12125 , thanks for reporting. Those tests in particular require a multi-vault server setup along with consul, to test cluster operations, so they are more likely to have some flakiness. In #1105 I parallelized the tests, which made these even flakier, so I also added more retries throughout the test suite, and that typically handles it. I don't recall seeing any flakiness in our CI for those tests because the occasional flake is absorbed by retries within the tests themselves.

Are you seeing steady failures for those, or only occasional?

One thing you could try is disabling parallel execution and see if that helps these pass, though it would be slower. Add `-n0 --dist no` to your `pytest` invocation.

**Comment by yan12125** [comment]
Oops, I forgot to mention that I already disabled parallel tests after seeing other errors. Specifically, I dropped all pytest flags in `pyproject.toml`. https://gitlab.archlinux.org/archlinux/packaging/packages/python-hvac/-/blob/47f965313fc450de2fbc2f1b1325549577c6541a/PKGBUILD#L35

> Are you seeing steady failures for those, or only occasional?

Kind of often, maybe 6 or 7 out of 10 runs

**Comment by yan12125** [comment]
I guess the issue may be specific to Arch Linux. I can reproduce the errors on both high-end and low-end machines (AMD 9454P, AMD 7950X3D, Intel i7-4770).

On the other hand, I found if I add a sleep, tests are more likely to pass
```diff
diff --git a/tests/utils/hvac_integration_test_case.py b/tests/utils/hvac_integration_test_case.py
index 76a5643..f76c5fa 100644
--- a/tests/utils/hvac_integration_test_case.py
+++ b/tests/utils/hvac_integration_test_case.py
@@ -46,6 +46,7 @@ class HvacIntegrationTestCase:
         while True:
             try:
                 cls.manager.start()
+                time.sleep(1)
                 cls.manager.initialize()
                 cls.manager.unseal()
             except Exception as e:
```

**Comment by yan12125** [comment]
Got it - I can reproduce the errors on GitHub Actions after switching to Arch Linux: https://github.com/yan12125/hvac/commits/try-issue1141/

**Comment by briantist** [comment]
Excellent, thank you so much!

> On the other hand, I found if I add a sleep, tests are more likely to pass

I usually try not to add arbitrary sleeps when I can avoid it but this is still very helpful. I would prefer to add retries to the `unseal` method instead. Based on your GHA output, the problem seems to always happen in the `unseal` method and not `initialize`, and [`unseal` always creates its own hvac `Client`](https://github.com/hvac/hvac/blob/main/tests/utils/server_manager.py#L380), so we can tell it to [initialize that with retries, as described here](https://hvac.readthedocs.io/en/stable/advanced_usage.html#retrying-failed-requests), but instead of the retry settings shown there, we really only want it to retry on connection refused, so have to play with the `Retry` settings.

This way we don't `sleep` unnecessarily, only as part of retrying.

---

If you're interested in putting up a PR for that I'd be very grateful.

**Comment by yan12125** [comment]
Many thanks for the hint about retries! I got a working patch:
```diff
diff --git a/tests/utils/__init__.py b/tests/utils/__init__.py
index 723bf65..aa813f7 100644
--- a/tests/utils/__init__.py
+++ b/tests/utils/__init__.py
@@ -80,7 +80,7 @@ def get_generate_root_otp():
     return test_otp
 
 
-def create_client(url, use_env=False, **kwargs):
+def create_client(url, use_env=False, session=None, **kwargs):
     """Small helper to instantiate a :py:class:`hvac.v1.Client` class with the appropriate parameters for the test env.
 
     :param url: Vault address to configure the client with.
@@ -105,10 +105,15 @@ def create_client(url, use_env=False, **kwargs):
                         **kwargs,
                     )
     else:
+        if session:
+            session.cert = (client_cert_path, client_key_path)
+            session.verify = server_cert_path
+
         client = Client(
             url=url,
             cert=(client_cert_path, client_key_path),
             verify=server_cert_path,
+            session=session,
             **kwargs,
         )
     return client
diff --git a/tests/utils/server_manager.py b/tests/utils/server_manager.py
index d402174..10a6f56 100644
--- a/tests/utils/server_manager.py
+++ b/tests/utils/server_manager.py
@@ -18,6 +18,9 @@ from tests.utils import (
 
 from hvac.v1 import Client
 
+from requests.adapters import HTTPAdapter
+from urllib3.util import Retry
+
 logger = logging.getLogger(__name__)
 
 
@@ -377,5 +380,12 @@ class ServerManager:
         """Unseal the vault server process."""
         vault_addresses = self.get_active_vault_addresses()
         for vault_address in vault_addresses:
-            client = create_client(url=vault_address)
+            adapter = HTTPAdapter(
+                max_retries=Retry(total=3, connect=3, backoff_factor=0.1)
+            )
+            session = requests.Session()
+            session.mount("http://", adapter)
+            session.mount("https://", adapter)
+
+            client = create_client(url=vault_address, session=session)
             client.sys.submit_unseal_keys(self.keys)
```
Do you think this approach is good for a pull request?

**Comment by briantist** [comment]
Great work @yan12125 ! Yes, from a quick view, I think this is a good approach. Please submit it as a PR and I will look it over as soon as I can, thank you!

**Comment by yan12125** [comment]
Thanks! Let me add some comments first.
