### ISSUE TITLE
hvac 2.2.0 flagging for vulnerability

### ISSUE THREAD

**Issue by sfjkastello** [hvac/hvac#1168]
hvac@2.2.0 > requests@2.31.0 > certifi@2020.6.20

https://snyk.io/vuln/SNYK-PYTHON-CERTIFI-5805047

Fix: Upgrade certifi to version 2023.7.22 or higher.

**Comment by briantist** [comment]
We had already been using an unaffected version of `certifi` in our lock file since this PR at least:
- https://github.com/hvac/hvac/pull/1048

That should have been in `hvac==2.0.0`.

We don't specify `certifi` as a direct dependency of the package though, it may be possible that something else is in your environment or container constrained the package, or maybe it was already installed and satisfied all the version constraints in the env/container that you scanned with Snyk.

I'll close this out for now, if you think that's in error please let me know.
