### ISSUE TITLE
Writing data payload without specifying a key value

### ISSUE THREAD

**Issue by rcallphin** [hvac/hvac#138]
We want to upstream some code to RachHD for an integration with Vault that we wrote. We would like to use the python HVAC client but have found some differences between what is returned from HVAC client as apposed to the RESTapi.

Currently we have something like this: 
def rackhd_provision_coreos(): 
vault_wrapping_url = 'https://REDACTED/v1/sys/wrapping' 

with open(options.ignition_file, 'r') as f: 
ignition_data = load(f) 
wrap = vault_client.write('sys/wrapping/wrap', ignition_data=ignition_data, wrap_ttl='1h') 
14 vault_wrapping_token = wrap['wrap_info']['token']

We want to be able to include a data payload without specifying a key value (in my example, the portion `ignition_data=`)

The API already supports this: 
VAULT_WRAPPING_TOKEN=$(curl --header "X-Vault-Token: ${VAULT_TOKEN}" \ 
--header "X-Vault-Wrap-TTL: 1h" \ 
--request POST \ 
--data @$2 \ 
${VAULT_WRAPPING_ADDR}/wrap \ 
| jq -er '.wrap_info.token')

The key name in the case of the REST API is `data`. 
The case of HVAC, there’s a key called `data`, followed by another key matching the name of the key you pass in. Which makes it hard to know what to look for.

Example: 
{"request_id":"e5481d68-24e0-8a4b-c35c-8b53a68341ee","lease_id":"","renewable":false,"lease_duration":0,"data":{"ignition":

{"request_id":"46a4ce29-8330-064f-1bb4-167748b8435d","lease_id":"","renewable":false,"lease_duration":0,"data":{"key_name":"{\n \"ignition\":

**Comment by otakup0pe** [comment]
Is this something that is related to #133 (or one of the linked issues) ?

**Comment by kaypeter87** [comment]
This seems related with #133 and might be resolved with #1028. 

cc: @briantist

**Comment by kaypeter87** [comment]
Closing due to above, but happy to reopen if #1028 doesn't resolve this issue.

**Comment by briantist** [comment]
It's a little difficult to tell if this issue would be fixed by the mentioned PR, because in the OP we cannot see what the contents of the ignition data file are.

The wrapping API endpoint still needs a JSON object,. Even if we presume that the data in the file is in fact a valid JSON object, the two example calls do different things since the Python example is reading the `str` or `bytes` content of the file and not deserializing it, while the CLI example expects to read the file content as a string and the CLI handles deserialization, so even without the "extra key" issue, the end result would not be the same.

That said, the issue mentioned could have been solved with the original `write` method _if_ the data had been deserialized:
```
with open(options.ignition_file, 'r') as f:
    ignition_data = json.load(f)

wrap = vault_client.write('sys/wrapping/wrap', wrap_ttl='1h', **ignition_data)
vault_wrapping_token = wrap['wrap_info']['token']
```

With `ignition_data` containing a `dict`, we can now use `**` to unpack it and use it to assign `kwargs` in the `write` call.

With the [changes being made to the write method](https://github.com/hvac/hvac/issues/1034), starting in #1028, the situation is mostly the same, but it may look a bit more natural since we're directly setting an argument called `data`:

```
with open(options.ignition_file, 'r') as f:
    ignition_data = json.load(f)

wrap = vault_client.write_data('sys/wrapping/wrap', wrap_ttl='1h', data=ignition_data)
vault_wrapping_token = wrap['wrap_info']['token']
```

---

In any case, I think we'll keep this issue closed as it's solvable even without the upcoming changes if I understood it correctly. @rcallphin please feel free to comment if this doesn't cover it; sorry for the very long delay in response. Thanks for reviewing this @kaypeter87 !
