### ISSUE TITLE
Policy syntax

### ISSUE THREAD

**Issue by Rick-OS** [hvac/hvac#160]
Hi there, 
Was hoping some some help with the policy creation syntax. Im trying to incorporate a variable into the policy as shown below.
Can you please assist, as i get slice errors when parsing. 

policy = 
    path transit/encrypt/ + key {
      capabilities = "update"
    }

**Comment by jeffwecan** [comment]
Looking over this issue again (and with some more recent exposure to creating policies via HVAC) I believe the answer to your question is something along these lines:

```python
import hvac

client = hvac.Client()

policy_body = """
path transit/encrypt/{key} {
capabilities = "update"
}
""".format(key=key)
client.set_policy(name='my-policy-name', rules=policy_body)
```

I'll go ahead and use this issue to track adding in an example in the docs to that effect.

The only other aspect I can imagine this issue was getting at involves https://www.vaultproject.io/docs/concepts/policies.html#templated-policies. I wouldn't be able to comment to that end without further clarification however.
