### ISSUE TITLE
`requests` version constraint update

### ISSUE THREAD

**Issue by jeffwecan** [hvac/hvac#770]
Ideally we update our `setup_requires` entry for `requests` to >= `2.25.0` as part of: https://github.com/advisories/GHSA-q2q7-5pp4-w6pg

Related discussion over yonder in: https://github.com/hvac/hvac/pull/767#issuecomment-926006197

**Comment by briantist** [comment]
Following up from https://github.com/hvac/hvac/pull/767#issuecomment-926050407 here, since that's a closed issue. Thansk for opening this one!

> Also, if you can expand a bit on the "broke stuff by way of other (unrelated) packages needing a version that conflicts" note with any example of impacted packages I would appreciate having that extra context.

Sure, I can expand on this. Fair warning, it's probably a "not your problem" type of thing, so my questioning the need for the version bump is just to see if it's necessary or what it adds.

I maintain [Ansible's `community.hashi_vault`](https://github.com/ansible-collections/community.hashi_vault) collection, which relies on `hvac`. In older (but still supported) versions of Ansible, the pre-built test-container has a library `hcloud` pre-installed, and that version has a constraint on `requests` that's incompatible with `2.25`. I don't use or need that library, but the `pip` failure causes my test invocation to fail, causing CI to fail.

It leaves me with having to work around the situation by trying to use custom/unsupported containers, or by having my test requirements include versions of `hcloud` that are both compatible with the python versions I test against and also allow for a `requests` version that's compatible with `hvac`. The latter workaround is what I put together: https://github.com/ansible-collections/community.hashi_vault/pull/147

I doubt I'll be able to avoid that situation forever, but the longer the better.

---

Thanks for including the CVE link and having that context included. Might be a naive question, but can we specify external `urllib` instead of relying on the embedded version? I'm not certain I fully understand the pros and cons of that.

**Comment by briantist** [comment]
Resolved in #897
