### ISSUE TITLE
Repository Contributors Wanted!

### ISSUE THREAD

**Issue by jeffwecan** [hvac/hvac#809]
Howdy Folks:

I've been the primary maintainer of this `hvac` Python module since 'round the time of https://github.com/hvac/hvac/issues/188. Especially over the past year or so, I have increasingly recognized that I no longer have the requisite time available to keep it properly maintained. So with that said, **I would dearly like to find some folks to take over the maintainership of this project**.

Please let me know if you're one of those folks, either in reply to this issue (or via an email to jeffwecan@python-hvac.org if perferred), and we can work out getting you set up with the access needed to help maintain the GitHub organization, PyPI project, etc!

I'd also like to again thank all the wonderful contributors who have helped move this project forward during my tenure. Also, my sincere apologies to folks who have contributed over recent history that haven't had seen those contributions integrated in a timely manner.

----

![giphy help wanted](https://media4.giphy.com/media/xThta04bpUbHimyW7m/giphy.gif?cid=ecf05e47ljucntwh0zlan2jc6iassd8b67g5wgd5l70699vt&rid=giphy.gif&ct=g)

**Comment by rajmaradia** [comment]
Hey Jeff, I am interested. I have sent you an email. 
-Raj

**Comment by colin-pm** [comment]
Sent an email as well.  Would be happy to help as much as I can!

**Comment by ahamilto** [comment]
I am also interested in helping to maintain this if you are still looking for assistance.

**Comment by sohilkaushal** [comment]
Hey Jeff,

I am quite interested as well... if you're still down for it happy to pass through the details

**Comment by briantist** [comment]
I'm also interested! Just seeing this now

**Comment by devlounge** [comment]
I'm interested!

**Comment by intgr** [comment]
As I understand, @colin-pm is now the new maintainer of this library? But progress doesn't seem to have sped up a great deal.

It would be great to have some indication about the future of this library. Will there be a new `0.x` release soon? Lots of improvements are already waiting in the develop branch, but it has been 11 months since the last release.

Or are we waiting for everything to align for the 1.0 release? What's the roadmap there, what are the blocker issues or missing features?
