### ISSUE TITLE
create_ca_certificate_role() fails with 'File name too long' on macOS

### ISSUE THREAD

**Issue by intgr** [hvac/hvac#841]
The `Client.auth.cert.create_ca_certificate_role()` method fails on macOS when I pass a certificate PEM string as the `certificate=` argument.

The method tries to be helpful and open the passed-in certificate argument as a file path:
```python
        try:
            with open(certificate, 'r') as f_cert:
                cert = f_cert.read()
        except FileNotFoundError:
            cert = certificate
```

But instead of `FileNotFoundError`, an `OSError` gets thrown:

> OSError: [Errno 63] File name too long: '-----BEGIN CERTIFICATE-----\nMII[...snip...]\n-----END CERTIFICATE-----\n'

I'm not sure what the proper fix for this would be. I assume it's not a good idea to break backwards compatibility with the path option of the `certificate` argument?

Maybe a new argument `certificate_str` that always gets used as-is? Or should we do some crazy detection logic like check if `\n` exists in the string, and avoid trying to open it?

**Comment by colin-pm** [comment]
Hi @intgr, since the contents of a certificate string will be standardized, we could add a regex to filter certificates and certificate file names. I think that would be a little better than trying to open whatever is passed as the `certificate` parameter. I think that would be a good short-term fix for now.

For the long-term I would rather us not use a single parameter for certificate contents or a path to the certificate file. I do think it'd be better to have a `certificate` parameter for certificate strings and a `certificate_file` param for certificate files.

Along with the short-term regex patch, we could add the `certificate_file` parameter. If what's passed to `certificate` parameter is a file, we can pass a deprecation warning to the user, suggesting for them to use the new certificate_file parameter. Then in the next major release we can pull support for passing certificate files with the `certificate` parameter.

@briantist What are your thoughts on these changes?

**Comment by briantist** [comment]
That sounds pretty good to me!
