### ISSUE TITLE
Sam local invoke failed :  No module named 'hvac'

### ISSUE THREAD

**Issue by Suttonz** [hvac/hvac#895]
I am trying to build AWS lambda (python) and test it locally with Docker, but when I do "import hvac", the lambda can build with "sam build", but when I do "sam local invoke", it always returns an error message as follows. When I remove hvac altogether, the lambda just works fine. My lambda needs to store newly generated AWS credentials in Vault, but I can't test it locally, anyone please can help or fix this bug? Much appreciated
```
{"errorMessage": "Unable to import module 'app': No module named 'hvac'", "errorType": "Runtime.ImportModuleError", "requestId": "d5d438a7-c05e-4720-97d7-6b329e608d8a", "stackTr.ace": []}%  

```

**Comment by colin-pm** [comment]
Hi, I would guess that your lambda does not have hvac properly installed. I would check that the hvac module is included in your lambda.

If you have any issues, I would suggest starting with the template project provided by `sam init` and including hvac in hello_world/requirements.txt. I was able to do this, build, and invoke the lambda with hvac included.
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html

Since this appears to be an issue with AWS SAM and not HVAC, I'm closing this issue.
