### ISSUE TITLE
auth/userpass is expecting a namespace in the token

### ISSUE THREAD

**Issue by d-bourdon** [hvac/hvac#937]
Hello,

I have a bug when I try to auth with the auth/userpass endpoint.

```Traceback (most recent call last):
  File "/home/dbourdon/Documents/vault_client.py", line 16, in <module>
    vault_client.auth.userpass.login("simvault-dev", password)
  File "/home/dbourdon/.local/lib/python3.10/site-packages/hvac/api/auth_methods/userpass.py", line 141, in login
    return self._adapter.post(
  File "/home/dbourdon/.local/lib/python3.10/site-packages/hvac/adapters.py", line 110, in post
    return self.request('post', url, **kwargs)
  File "/home/dbourdon/.local/lib/python3.10/site-packages/hvac/adapters.py", line 353, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
  File "/home/dbourdon/.local/lib/python3.10/site-packages/hvac/adapters.py", line 315, in request
    utils.raise_for_error(
  File "/home/dbourdon/.local/lib/python3.10/site-packages/hvac/utils.py", line 47, in raise_for_error
    raise exceptions.InternalServerError(message, errors=errors, method=method, url=url)
hvac.exceptions.InternalServerError: error performing token check: failed to look up namespace from the token: no namespace, on post https://vault.*********/v1/auth/userpass/login/*******```
```
I've confirmed the credential but using directly the HTTP API with curl, and the vault server is returning a token that works.

## To reproduce
Hvac=v1.0.2, Vault server=1.10.1
```python
import hvac

user="****"
password="****"

vault_client = hvac.Client(url="https://vault.*******", namespace=None) #tried also to not specify the namespace
vault_client.auth.userpass.login(user, password)
```

## Current Workaround
To mitigate that for now, I send the same credential via the REST api, parse the response and init hvac with the given token
```python

import json
import os
import hvac
from urllib import request

vault_client = hvac.Client(url="https://vault.************", namespace=None)

password="****"
user="****"

payload = {"password": password}
url = f"https://vault.*******/v1/auth/userpass/login/{user}"
req = request.Request(url, json.dumps(payload).encode("utf-8"))
req.add_header('Content-Type', 'application/json')

with request.urlopen(req) as response:
    body = response.read()

decode_body = json.loads(body.decode("utf-8"))
tmp_token = decode_body["auth"]["client_token"]

vault_client.token = tmp_token
list_response = vault_client.secrets.kv.v2.list_secrets(path='dev/email', mount_point="dev")
```

**Comment by briantist** [comment]
@d-bourdon thanks very much for the details and code samples. From looking through it all, I can't come up with a great reason why that would be happening.

I will see if I can reproduce this locally, but at the moment I'm not aware of an issue with it and know of it working in other places.

In the meantime, could you try two things?

1. After creating the client, call `vault_client.logout()`, and then try the login (this really shouldn't work)
2. Spin up a Vault server in dev mode (it can be a container on your machine or use your local Vault binary) and see if you can reproduce it against that, not using your real Vault server

**Comment by d-bourdon** [comment]
@briantist Sorry for the delay.

I've run the different tests and the results are interesting:
1. Weirdly, it works. I've done the same thing with the local vault, and no error raised.
2. With a vault server 1.12.4 running locally, it works directly, without logout. And it is still not working on my vault.

Now, vault has 2 new major, so I could try to bump my vault.

Also, I add a precision if it changes anything, as my vault is in HA mode through database.

**Comment by briantist** [comment]
Thanks for the update! It sounds like the issue is possibly something related to your Vault server configuration, but more likely your local (client) environment, specifically the stored token (probably put into the token sink by a previous `vault login` call).

`hvac` (unfortunately imo) automatically loads the token if it exists, and that can give some unexpected results when you have an existing token. Running `logout()` doesn't actually do anything in terms of contacting Vault, it clears any stored token in the `hvac` Client, including a token which may have been put there implicitly. 

You may also want to check your environment for the env vars `VAULT_TOKEN` and `VAULT_DEV_ROOT_TOKEN_ID`. If those are set, try `unset`ting them, and see how they are getting loaded into your environment in the first place.

Vault changed their token format (see [Server Side Consistent Token FAQ](https://developer.hashicorp.com/vault/docs/faq/ssct)) in 1.10, and the new format includes the namespace info in the token.

So your error message to me indicates that Vault is expecting the namespace information to be in the token, but it's not there, probably because you're supplying an old token, in the old format, which would have otherwise given you an error about an expired token or a permission denied or something.

For 2), by spinning up a Vault dev server, it should have set its own root token value which would have been found, so no error message because it used the new, valid token when you ran `hvac` or CLI from there.

---

Anyway these are my theories, but you should be able to confirm in your environment.

**Comment by d-bourdon** [comment]
It is so much clear now.

I've tried to load the same script inside a python container and yeah, the connection is working properly.

In my case, hvac loads token from my pc, from somewhere (`VAULT_TOKEN` and `VAULT_DEV_ROOT_TOKEN_ID` not in my env).

So, to resolve my issue, I will call logout prior to login as it will be on different environment but could be a good feature to be able to disable the autoloading of token.

Thank you very much for your help.

**Comment by briantist** [comment]
Thanks for confirming @d-bourdon , I agree we should have a way to opt out of that, and I've created an issue to track that if you want to subscribe to it:
- #958
