### ISSUE TITLE
New API proposal

### ISSUE THREAD

**Issue by ianunruh** [hvac/hvac#95]
Hi all,

This library has been around for around 1.5 years now and in that time, Vault has changed quite a bit. The number of features and API surface has grown a huge amount. Just in the HVAC client class, there's 98 methods, each for a different API call. The problem is that the API is starting to become a bit unwieldy.

I'd like to get some feedback from the users of this library to figure out a better path going forward keep this client simple to use and maintainable as Vault adds more features in the future. I'd like to propose something similar to [Consulate](https://github.com/gmr/consulate)'s API (a Consul client library/CLI for Python).

We could start by breaking up related functionality into subclasses and then deprecate the old monolithic methods over time, as we get closer to a 1.0 release.

Here's an example of what the new API could look like:

```python
client = hvac.Client()

client.read('mykey')
client.write('mykey', foo='bar')

client.secret_backends.list()
client.secret_backends.enable('mysql')
client.secret_backends.disable('...')

client.token_roles.list()

client.app_roles.list()
client.app_roles.create('test')
client.app_roles.auth()
```

**Comment by ianunruh** [comment]
@mwielgoszewski @nicr9 @mtougeron @otakup0pe @blarghmatey

**Comment by nicr9** [comment]
This sounds like a great idea! :+1:

**Comment by otakup0pe** [comment]
I'm game! As long as we pay attention to semantic versioning as we roll this out ;)

**Comment by blarghmatey** [comment]
👍

**Comment by nicr9** [comment]
I've tried to get the ball rolling with #96 

Let me know what you guys think!

**Comment by mtougeron** [comment]
@ianunruh I like it.
@otakup0pe totally agree semantic versioning will be key.

Would be nice to also standardize some of the names for the method params too if time permits.

Also, let me know if you have a chunk that you'd like me to help out with. I'm happy to spend some time on it this weekend.

**Comment by dsuch** [comment]
Hello,

this is just a reply from a user of the library, as originally requested.

While you are working on re-designing the API, could you please make __request and __raise_error methods read _request and _raise_error, respectively?

That is, I understand that they are private but the fact of like is that clients in this kind of libraries get embedded in larger projects and frameworks which means they also tend to get sub-classed to add custom functionality (e.g. bespoke headers or replacing the series of if's in __raise_error with a lookup dictionary),  and making methods private to a class simply makes it all a bit more cumbersome.

Other than that, the project looks very nice, nice job! :-)

**Comment by nicr9** [comment]
Would it be a good idea to keep the API changes in a specific branch until they've been finished? That way people using the master branch won't have to put up with iterative changes to the API over time and when we're all happy with it we can merge and bump the major version number.

**Comment by jeffwecan** [comment]
Here are my tentative plans for moving hvac in this direction:

* General structure to be model on https://github.com/gmr/consulate/ since they seem to have a good thing going on generally. There also would seem to be a benefit to sharing a similar structure across Python client libraries for HashiCorp applications.
* New arrangement of methods/classes to be added into the mainline hvac releases.
* To enable the above, previous call sites will be kept in place, with a deprecation warning included for two minor revisions. E.g., if a method is marked a deprecated in 0.6.2, it will be removed in 0.8.0. For something added in 0.8.17, removal would occur in 1.0.

With that understanding, I'd like to see the general structure of the module completely reshaped before the 0.9 release. That would enable most of the refactored code to be completed cleaned up by the time we're ready for 1.0.

**Comment by jeffwecan** [comment]
Reading back through this thread, @dsuch's point will end up being accommodated if https://github.com/ianunruh/hvac/pull/223 goes through as-is so thats a bonus :D.

**Comment by jeffwecan** [comment]
I'm pretty content with the examples contained in the linked PR's of how to manage this issue moving forward. Closing it out until/unless anyone has any additional input on the matter.
