### ISSUE TITLE
Permission denied when authenticating in client but not in cli

### ISSUE THREAD

**Issue by sofialouisyax** [hvac/hvac#971]
Hi!

If I authenticate in the cli and use that token in the client init, I can read my secret as expected. When I use the hvac client to authentucate my app_role, I get "permission denied" when I attempt to read a secret.  If I initiate the client using the token I generated from this login, I also get "permission denied"

Expected behaviour is that I can read my secret in all three cases.

Is there anything I am doing wrong?

Best regards,
Sofia

version:
```
Name: hvac
Version: 1.1.0
```

```
Traceback (most recent call last):
  File "sandbox.py", line 28, in <module>
    print(new_client.secrets.kv.v2.read_secret_version(path=P, mount_point=MP, raise_on_deleted_version=True))
  File "/home/sofialo/.local/lib/python3.8/site-packages/hvac/api/secrets_engines/kv_v2.py", line 153, in read_secret_version
    return self._adapter.get(
  File "/home/sofialo/.local/lib/python3.8/site-packages/hvac/adapters.py", line 110, in get
    return self.request("get", url, **kwargs)
  File "/home/sofialo/.local/lib/python3.8/site-packages/hvac/adapters.py", line 372, in request
    response = super().request(*args, **kwargs)
  File "/home/sofialo/.local/lib/python3.8/site-packages/hvac/adapters.py", line 340, in request
    self._raise_for_error(method, url, response)
  File "/home/sofialo/.local/lib/python3.8/site-packages/hvac/adapters.py", line 258, in _raise_for_error
    utils.raise_for_error(
  File "/home/sofialo/.local/lib/python3.8/site-packages/hvac/utils.py", line 41, in raise_for_error
    raise exceptions.VaultError.from_status(
hvac.exceptions.Forbidden: 1 error occurred:
        * permission denied

, on get https://[...].com/v1/opinfra/data/ansible/statuspage/api_keys
```

```
import hvac

HVAULT_ROLE_ID="488..."
HVAULT_SECRET_ID="dde..."
MP = "opinfra"
P = "ansible/..."
URL = "https://[...].com"

CLI_TOKEN = "hvs.CAES...R2E"
client = hvac.Client(url=URL, token=CLI_TOKEN)

# success
print(client.secrets.kv.v2.read_secret_version(path=P, mount_point=MP, raise_on_deleted_version=True))

new_client = hvac.Client(url=URL)
resp = new_client.auth.approle.login(role_id=HVAULT_ROLE_ID, secret_id=HVAULT_SECRET_ID)
print(new_client.token)

# fail
print(new_client.secrets.kv.v2.read_secret_version(path=P, mount_point=MP, raise_on_deleted_version=True))

newer_client = hvac.Client(url=URL, token=new_client.token)
# fail
print(newer_client.secrets.kv.v2.read_secret_version(path=P, mount_point=MP, raise_on_deleted_version=True))

```

**Comment by briantist** [comment]
Hi @sofialouisyaxis !

Thank you for providing the code and detailed error!
This does seem strange to me. I looked through the code here in `hvac` and in [another project I maintain](https://github.com/ansible-collections/community.hashi_vault) that uses `hvac` heavily including for approle auth, and I don't see anything that would cause this in the library.

Since the `hvac` login method is not failing, and is giving you a token, I imagine then that the policies applied to the tokens are different for some reason.

Let's start by checking that for both tokens. In the CLI you can use [`vault token lookup`](https://developer.hashicorp.com/vault/docs/commands/token/lookup) or in `hvac` you can use [`client.auth.token.lookup_self()`](https://hvac.readthedocs.io/en/stable/source/hvac_api_auth_methods.html#hvac.api.auth_methods.Token.lookup_self).

I think this will give us the first clue by showing us how these tokens are different.

Could you also check whether your shell session has either of these environment variables set?
* `VAULT_TOKEN` 
* `VAULT_DEV_ROOT_TOKEN_ID`
(or any other vars beginning with `VAULT_`)

**Comment by sofialouisyaxis** [comment]
When the admin removed a trailing "/" in the end of the search path that the app role had access to, this solved the issue.

The inconsistent behavior is still a bit strange, but it is solved now :)

**Comment by sofialouisyaxis** [comment]
I can unfortunately not debug the issue more with your instructions, since I would need to ask the admin to recreate the solved problem, but maybe the solution gives a clue on what the inconsistency could be. But hopefully, if anyone else encounters the same problem, they can find this thread!

Best regards, 
Sofia

**Comment by briantist** [comment]
> When the admin removed a trailing "/" in the end of the search path that the app role had access to, this solved the issue.
> 
> The inconsistent behavior is still a bit strange, but it is solved now :)

It sounds like the policies that grant access did not include the trailing slash then. If the exact same URL was used in the CLI as in `hvac`, it's also possible that the CLI is doing some kind of truncation on trailing slashes but I'm not sure. Glad it's sorted though!
