### ISSUE TITLE
transit sign_data doesn't take the hash_algorithm in consideration

### ISSUE THREAD

**Issue by deidax** [hvac/hvac#989]
When running the following script:
`
sign_data_response = client.secrets.transit.sign_data(
    name='key-name',
    mount_point=app-transit',
    hash_algorithm='sha2-512',
    hash_input=hash_input=base64ify('hi its me hvac')
)
`

I get the following error

`hvac.exceptions.Forbidden: 1 error occurred: *permission denied on post http://mywebsite.com/v1/app-transit/sign/key-name
`

**Comment by briantist** [comment]
The description for this parameter says that it can _also_ be specified in the URL, not that it must be. The method seems to already submit it in parameters, so I'm wondering if maybe something else is going on here, or if the description of the parameter in HashiCorp's documentation is incorrect: https://developer.hashicorp.com/vault/api-docs/secret/transit#sign-data

Do you have any more info that might be helpful in reproducing this error?

**Comment by deidax** [comment]
When I try using the sign data function with the sha2-512 algorithm like this:
```
import hvac
client = hvac.Client(url='https://127.0.0.1:8200')

key_name = 'hvac-signing-key'
sign_data_response = client.secrets.transit.sign_data(
    name=key_name,
    mount_point=my_mount-point,
    hash_algorithm='sha2-512',
    hash_input=base64ify('hi its me hvac'),
)
signature = sign_data_response['data']['signature']
print('Signature is: {signature}'.format(signature=signature))
```
I get the following error
```
Forbidden: 1 error occurred:
    * permission denied
    on post http://127.0.0.1:8200/v1/key-name/sign/my_mount-point
```

**Comment by briantist** [comment]
@deidax thanks for the additional info. I've set up a Vault dev server to test this out, and what I've found is that `hvac`'s way of setting `hash_algorithm` does work.

I was able to confirm that it worked with both the path and parameter-based methods, and confirm that if the hash algorithm is set in both the path and as a parameter, the parameter is ignored. This was most easily tested by setting invalid algorithm names like `sha9`

```
$ vault write transit/sign/key2/sha1 plaintext=$(echo "abc" | base64) hash_algorithm=sha9
Key          Value
---          -----
signature    vault:v1:YCMVcigkAzgjGDgYNhjnSxF5v9dFgEkUavQF+zxMg2XjquPco8EBUaLYIeyxw7ikfO+iyK4HtvQGDlPvWeqCtWUrucFg8dR0WlnmxWQGTM/c5vT8LjdD4aT7iDrkdKn6zjvWuk4VtIJl4VGZBhrld6dnPe5DF7rl6BBRFOs4qo/lPtveidJGppLLRdLHlZdSvGQpnFA/FA/C5YnVWADHhyIgbEv1XNC+KMTBZdeWXfLQIVHnd8UR+9ifL+sP51/ohoX14r1NOqDcLdEDpbpXU8t/FUPpWuWEfa97n0sIbpqnjrfjb03fCSvQRRPgCZ6ZGhCM/KPkl28E7IK+4bz4zd4179qL0RwWvT8n2gkeex3A7WWztlamY9xrBmsos1RxHQ8S6ZHa4My/6vEC2zcp9jTstWdtIP9VLG2yCz8mGrnhewJxdT3rnLt65LAcZeL2mWRYhK3pIH3sH0HypOC+IvGd8on8s+U0P1oX4BzkDV5kA3zZPdcu1zb4WxEHAIhQc7DTGnPu8kEbcRCdu88T6s4LhCn90HAtpyoiJxsOZt00720DzQXZ58SI0awz8FBhu9RTgb6+HNWLEw0sLtwCo9VDqAsRkIVA7nHsRSEL+4KmuN1waOKGII6d0hVeE0Revcy5zHxmg0UecQBGnYwqPxmUJFeCZWHacr6rxi9cHtA=

$ vault write transit/sign/key2/sha9 plaintext=$(echo "abc" | base64) hash_algorithm=sha9
Error writing data to transit/sign/key2/sha9: Error making API request.

URL: PUT http://localhost:8200/v1/transit/sign/key2/sha9
Code: 400. Errors:

* invalid hash algorithm "sha9"

$ vault write transit/sign/key2/sha9 plaintext=$(echo "abc" | base64) hash_algorithm=sha10
Error writing data to transit/sign/key2/sha9: Error making API request.

URL: PUT http://localhost:8200/v1/transit/sign/key2/sha9
Code: 400. Errors:

* invalid hash algorithm "sha9"

$ vault write transit/sign/key2 plaintext=$(echo "abc" | base64) hash_algorithm=sha10
Error writing data to transit/sign/key2: Error making API request.

URL: PUT http://localhost:8200/v1/transit/sign/key2
Code: 400. Errors:

* invalid hash algorithm "sha10"

$ vault write transit/sign/key2 plaintext=$(echo "abc" | base64) hash_algorithm=sha1
Key          Value
---          -----
signature    vault:v1:Q+EoI8NQFbrMLZ/WLJEtLVYCgkdCgoP7O3aU2K/I6eTRxrTgGIJ6gf2M3fANpjAXW8qHqbILgS5GgPoDXH00t/GUhY3qbFdP8cu9dqq0NTEQpCzT0gVD8TgOqwxRCIx5yYYb2cYTXfbSBeKTfqj3pC82HylnhM5ZmWV7CqTkSsC9hx+tWBowSjNt3LhKAz6xSntsoXKduZCTfXVD4prijFAsIpVtaT088i9AcyhVQPjyzYx5m0oJSzj9cO/YWXSJ9STtbqNSTGoj80PiuFmgIvvuoJlC4fL0GtW7sd6Edr7xaBR+rAG+7MEl2/9KMWSM10zyH1s8B/pt5QaYRFYT9uZsPt60id73fifZcMjmar0D1QW5b8IFAHhGmSR4Y4qYG68nji19ALExd8Q4BN/JaKLFjQNfNgFeBe5SylCFDWZScmRfMKbC3aXB7oa+vQvs88eYOR5X3bDMc/iryjDApdBxfChrZucw2IJ1LXnME9mFSZrTfVUlXqOOBDy2f9UIzQOXzUSfX7jPXRD5FAwoHZ+fVi2O1u0UtNGDlT1Gd3UxPP/2NWJDAXzihjrfcZOTJzNec27sWXyfn4h9xjHKAKrPwwvAX3OAP2dmFilzwPAH8PTTVpngNHGI1waqhoVWq0eIcFaUr8YSELit56Z9FFfoqx16zhL/CdCpldxJ3tA=

$ vault write -output-curl-string transit/sign/key2 plaintext=$(echo "abc" | base64) hash_algorithm=sha1
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"hash_algorithm":"sha1","plaintext":"YWJjCg=="}' http://localhost:8200/v1/transit/sign/key2
```
---

The reason for your permission denied error is probably because your policies are set to allow only the path based format, I would say it's likely they are using `my_mount-point/sign/*` as the path that's allowed for your token. Unfortunately that path _will not_ allow access to `my_mount-point/sign` due to the trailing slash `/` in the policy. 

You may have to list both forms in your policy if you want to allow that.

Let me know if you can confirm the above.

---

We can also consider updating `hvac` to support both ways, but we have to figure out how a caller chooses the path form, I guess by additional parameter.

We cannot convert to use _only_ the path form as originally proposed in your PR because users who have policies that allow the shortened path form and _not_ the form with the algorithm would then have their calls break.

**Comment by deidax** [comment]
@briantist Thank you for pointing that out, It appears that the issue is related to the vault policies. unfortunately, I do not have the necessary access to modify or adjust those policies. To resolve the problem, I have made modifications to the sign_data function within the `hvac` package.

**Comment by briantist** [comment]
@deidax thanks for confirming! As mentioned, we can add support for path-based hash algorithm to `hvac`, but we cannot replace parameter-based completely.

Since this issue was largely a troubleshooting one, let's open a new issue for the feature request. Let me know if you would like to open it, or if I should do that.

**Comment by deidax** [comment]
@briantist yes let's open a new issue for the feature request so we can add support for path based hashing, as for now I will close this issue. Thank you for your feed back
